name: daily_farm

# Run this workflow every time a new commit pushed to your repository
on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  run_0:
    # Name the Job
    name: run_0
    # Set the type of machine to run on
    runs-on: ubuntu-18.04
    timeout-minutes: 120

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Check out my other private repo
        uses: actions/checkout@v2
        with:
          repository: brokenjade3000/got_auto
          token: ${{ secrets.BK3K_TOKEN }} # `GH_PAT` is a secret that contains your PAT
          path: got_auto    

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY }}
          GOTAUTH: ${{ secrets.GOTAUTH }}
          LOG_TOKEN: ${{ secrets.LOG_TOKEN }}
        run: |
          mv /home/runner/work/pub_hofs/pub_hofs/got_auto /home/runner/work/got_auto
          cd /home/runner/work/got_auto
          chmod 775 ./script/install.sh
          ./script/install.sh
      - name: Run daily_0
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_REPO: brocjad/pub_hof
          HOF_REPO: ${{ secrets.HOF_REPO }}
          HOF_HEADER: ${{ secrets.HOF_HEADER }}
        run: |
          pwd
          cd /home/runner/work/got_auto/src
          python --version
          sleep 0
          python run_daily_hof.py 0

  run_1:
    # Name the Job
    name: run_1
    # Set the type of machine to run on
    runs-on: ubuntu-18.04
    timeout-minutes: 120

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Check out my other private repo
        uses: actions/checkout@v2
        with:
          repository: brokenjade3000/got_auto
          token: ${{ secrets.BK3K_TOKEN }} # `GH_PAT` is a secret that contains your PAT
          path: got_auto    

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_REPO: brocjad/pub_hof
          HOF_REPO: ${{ secrets.HOF_REPO }}
          HOF_HEADER: ${{ secrets.HOF_HEADER }}
        run: |
          mv /home/runner/work/pub_hofs/pub_hofs/got_auto /home/runner/work/got_auto
          cd /home/runner/work/got_auto
          chmod 775 ./script/install.sh
          ./script/install.sh
      - name: Run daily_0
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_REPO: brocjad/pub_hof
          HOF_REPO: ${{ secrets.HOF_REPO }}
          HOF_HEADER: ${{ secrets.HOF_HEADER }}
        run: |
          pwd
          cd /home/runner/work/got_auto/src
          python --version
          sleep 0
          python run_daily_hof.py 1

  run_3:
    # Name the Job
    name: run_3
    # Set the type of machine to run on
    runs-on: ubuntu-18.04
    timeout-minutes: 120

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Check out my other private repo
        uses: actions/checkout@v2
        with:
          repository: brokenjade3000/got_auto
          token: ${{ secrets.BK3K_TOKEN }} # `GH_PAT` is a secret that contains your PAT
          path: got_auto    

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_REPO: brocjad/pub_hof
          HOF_REPO: ${{ secrets.HOF_REPO }}
          HOF_HEADER: ${{ secrets.HOF_HEADER }}
        run: |
          mv /home/runner/work/pub_hofs/pub_hofs/got_auto /home/runner/work/got_auto
          cd /home/runner/work/got_auto
          chmod 775 ./script/install.sh
          ./script/install.sh
      - name: Run daily_0
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_REPO: brocjad/pub_hof
          HOF_REPO: ${{ secrets.HOF_REPO }}
          HOF_HEADER: ${{ secrets.HOF_HEADER }}
        run: |
          pwd
          cd /home/runner/work/got_auto/src
          python --version
          sleep 0
          python run_daily_hof.py 3
