name: send_test

# Run this workflow every time a new commit pushed to your repository
on:
  repository_dispatch:
    types: test


jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  send_1:
    # Name the Job
    name: send_test
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6


          
      # Runs the Super-Linter action
      - name: Run hof2
        if: ${{ contains(github.event.client_payload.id, ',2,') }}
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
        run: |
          echo ${{ github.event.client_payload.id }
          echo '2'
          

          
       # Runs the Super-Linter action
      - name: Run hof2
        if:  ${{ contains(github.event.client_payload.id, ',3,') }}
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
        run: |
          echo ${{ github.event.client_payload.id }
          echo '3'
